name: Réentraîner le modèle

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Réentraîner le modèle
      run: |
        python train_model.py --retrain
    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model  # Nom de l'artefact
        path: data/models  # Chemin vers le modèle et les autres fichiers
